

INSERT INTO public.authorities (authority, username) VALUES ('ROLE_USER', 'user');
INSERT INTO public.authorities (authority, username) VALUES ('ROLE_ADMIN', 'root');



INSERT INTO public.genres (id, name) VALUES (2, 'Action');
INSERT INTO public.genres (id, name) VALUES (8, 'Adventure');
INSERT INTO public.genres (id, name) VALUES (3, 'Animation');
INSERT INTO public.genres (id, name) VALUES (4, 'Biography');
INSERT INTO public.genres (id, name) VALUES (5, 'Comedy');
INSERT INTO public.genres (id, name) VALUES (6, 'Crime');
INSERT INTO public.genres (id, name) VALUES (7, 'Drama');
INSERT INTO public.genres (id, name) VALUES (9, 'Family');
INSERT INTO public.genres (id, name) VALUES (10, 'Fantasy');
INSERT INTO public.genres (id, name) VALUES (11, 'Historical');
INSERT INTO public.genres (id, name) VALUES (12, 'Horror');
INSERT INTO public.genres (id, name) VALUES (13, 'Music');
INSERT INTO public.genres (id, name) VALUES (14, 'Mystery');
INSERT INTO public.genres (id, name) VALUES (15, 'Sci-Fi');
INSERT INTO public.genres (id, name) VALUES (16, 'Sports');
INSERT INTO public.genres (id, name) VALUES (17, 'Thriller');
INSERT INTO public.genres (id, name) VALUES (18, 'War');
INSERT INTO public.genres (id, name) VALUES (19, 'Western');
INSERT INTO public.genres (id, name) VALUES (20, 'Documentary');



-- INSERT INTO public.movie (id, description, director, duration, image_url, release_date, title) VALUES (1, '93508', 'Steve Job', 90, 'kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg', '1990-01-01', 'Poor Things');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (2, '2024-10-10', 110, 'Eddie en Venom worden gezochte vluchtelingen. Opgejaagd door hun beide werelden en met het net dat zich sluit, wordt het duo gedwongen tot een verwoestende beslissing die het lot van hun partnerschap en zelfs hun leven zal bepalen.', 'Kelly Marcel', 'swi9bJvi1aoyMpW7PpURR9JgOrF.jpg', 'Venom: the Last Dance');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (3, '2021-12-22', 148, 'Neo moet opnieuw de weg naar de waarheid ontdekken wanneer de realiteit zoals hij die kende in twijfel wordt getrokken.', 'Lana Wachowski', 'rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg', 'The Matrix Resurrections');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (4, '2021-10-22', 155, 'Paul Atreides, een briljante en begaafde jonge man, moet naar de gevaarlijkste planeet in het universum reizen om de toekomst van zijn familie en zijn volk te verzekeren.', 'Denis Villeneuve', 'd5NXSklXo0qyIYkgV94XAgMIckC.jpg', 'Dune');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (5, '2021-12-17', 148, 'Peter Parker moet vechten tegen schurken uit andere universa terwijl hij worstelt met het behouden van zijn geheime identiteit.', 'Jon Watts', '1g0dhYtq4irTY1GPXvft6k4YLjm.jpg', 'Spider-Man: No Way Home');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (6, '2022-03-04', 176, 'Batman moet het opnemen tegen de Riddler terwijl hij een complot ontdekt dat het hele Gotham City in gevaar brengt.', 'Matt Reeves', '74xTEgt7R36Fpooo50r9T25onhq.jpg', 'The Batman');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (7, '2022-06-10', 146, 'De dinosaurussen zijn vrijgelaten in de wereld, en de mensheid moet een manier vinden om naast hen te overleven.', 'Colin Trevorrow', 'kAVRgw7GgK1CfYEJq8ME6EvRIgU.jpg', 'Jurassic World: Dominion');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (8, '2022-05-27', 131, 'Na meer dan dertig jaar dienst keert Maverick terug naar de luchtmacht om een nieuwe generatie piloten te trainen.', 'Joseph Kosinski', '62HCnUTziyWcpDaBO2i1DX17ljH.jpg', 'Top Gun: Maverick');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (9, '2022-11-11', 161, 'Na het verlies van koning T''Challa, moeten de mensen van Wakanda vechten om hun thuisland te beschermen.', 'Ryan Coogler', 'ps2oKfhY6DL3alynlSqY97gHSsg.jpg', 'Black Panther: Wakanda Forever');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (10, '2022-12-16', 190, 'Jake Sully leeft nu samen met zijn familie op Pandora. Ze moeten hun huis verlaten wanneer een nieuwe dreiging opduikt.', 'James Cameron', 'jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg', 'Avatar: The Way of Water');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (11, '2022-07-08', 119, 'Thor moet samenwerken met de Mighty Thor en anderen om het universum te redden van een nieuwe bedreiging.', 'Taika Waititi', 'pIkRyD18kl4FhoCNQuWxWu5cBLM.jpg', 'Thor: Love and Thunder');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (12, '2022-05-06', 126, 'Doctor Strange opent per ongeluk de poorten naar het multiversum, wat leidt tot een gevaarlijke reis door meerdere realiteiten.', 'Sam Raimi', '9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg', 'Doctor Strange in the Multiverse of Madness');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (13, '2021-10-08', 163, 'James Bond is gestopt, maar wordt opnieuw ingezet voor een missie om een mysterieuze schurk te stoppen die gewapend is met gevaarlijke technologie.', 'Cary Joji Fukunaga', 'iUgygt3fscRoKWCV1d0C7FbM9TP.jpg', 'No Time to Die');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (16, '2021-11-19', 124, 'Wanneer een familie naar een klein stadje verhuist, ontdekken ze hun band met de originele Ghostbusters.', 'Jason Reitman', 'sg4xJaufDiQl7caFEskBtQXfD4x.jpg', 'Ghostbusters: Afterlife');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (19, '2021-11-12', 118, 'Een Interpol-agent moet samenwerken met \''s werelds grootste kunstdief om een beruchte misdadiger te vangen.', 'Rawson Marshall Thurber', 'lAXONuqg41NwUMuzMiFvicDET9Y.jpg', 'Red Notice');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (28, '2021-05-28', 97, 'De Abbott-familie wordt opnieuw geconfronteerd met de wreedheden van de buitenwereld terwijl ze hun strijd om te overleven voortzetten.', 'John Krasinski', '4q2hz2m8hubgvijz8Ez0T2Os2Yv.jpg', 'A Quiet Place Part II');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (31, '2021-06-04', 112, 'Ed en Lorraine Warren proberen een zaak van demonische bezetenheid op te lossen die een rechtszaak zou kunnen veranderen.', 'Michael Chaves', 'xbSuFiJbbBWCkyCCKIMfuDCA4yV.jpg', 'The Conjuring: The Devil Made Me Do It');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (33, '2021-05-07', 119, 'Een mysterieuze bewaker van een geldtransportbedrijf ontrafelt een plot om miljoenen dollars te stelen.', 'Guy Ritchie', 'M7SUK85sKjaStg4TKhlAVyGlz3.jpg', 'Wrath of Man');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (32, '2021-07-23', 108, 'Een groep vakantiegangers ontdekt dat ze op een mysterieuze manier snel oud worden op een afgelegen strand.', 'M. Night Shyamalan', 'qPKw2w4Ya5ZoOaxUDK1czRskQBT.jpg', 'Old');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (30, '2021-09-10', 111, 'Een vrouw wordt geteisterd door schokkende visioenen van brute moorden en ontdekt al snel dat deze visioenen een gruwelijke waarheid verbergen.', 'James Wan', 'dGv2BWjzwAz6LB8a8JeRIZL8hSz.jpg', 'Malignant');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (34, '2021-03-05', 107, 'Een jonge krijger genaamd Raya moet de laatste draak vinden en haar volk verenigen om een kwaad te stoppen.', 'Don Hall', 'lPsD10PP4rgUGiGR4CCXA6iY0QQ.jpg', 'Raya and the Last Dragon');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (35, '2021-04-23', 110, 'Een nieuwe groep vechters moet deelnemen aan een dodelijk toernooi om het lot van de aarde te bepalen.', 'Simon McQuoid', 'nkayOAUBUu4mMvyNf9iHSUiPjF1.jpg', 'Mortal Kombat');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (36, '2021-06-25', 143, 'Dom Toretto wordt geconfronteerd met een nieuwe dreiging: zijn vervreemde broer Jakob, die een dodelijk complot smeedt.', 'Justin Lin', 'bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg', 'F9: The Fast Saga');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (37, '2021-07-23', 121, 'Een geheimzinnige ninja-oorlog krijger, bekend als Snake Eyes, moet een complot ontrafelen dat de toekomst van zijn clan in gevaar brengt.', 'Robert Schwentke', 'uIXF0sQGXOxQhbaEaKOi2VYlIL0.jpg', 'Snake Eyes: G.I. Joe Origins');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (38, '2021-10-01', 97, 'Eddie Brock komt tegenover de moorddadige symbioot Carnage te staan in dit explosieve vervolg.', 'Andy Serkis', 'rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg', 'Venom: Let There Be Carnage');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (39, '2021-07-30', 127, 'Een stel gaat op een gevaarlijke rivierexpeditie in de hoop een legendarische geneeskrachtige boom te vinden.', 'Jaume Collet-Serra', '9dKCd55IuTT5QRs989m9Qlb7d2B.jpg', 'Jungle Cruise');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (40, '2021-07-02', 138, 'Mensen uit de toekomst reizen terug naar het heden om soldaten te werven voor een oorlog tegen een buitenaardse dreiging.', 'Chris McKay', '34nDCQZwaEvsy4CFO5hkGRFDCVU.jpg', 'The Tomorrow War');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (42, '2020-12-25', 100, 'Een muzikant die zijn passie voor muziek heeft verloren, wordt uit zijn lichaam gehaald en moet de weg terugvinden met de hulp van een nieuwe ziel.', 'Pete Docter', 'hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg', 'Soul');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (43, '2020-12-25', 151, 'Diana Prince krijgt te maken met de Sovjet-Unie tijdens de Koude Oorlog in de jaren 80 en vindt een geduchte vijand in de vorm van Cheetah.', 'Patty Jenkins', '8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg', 'Wonder Woman 1984');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (44, '2020-09-04', 115, 'Een jonge Chinese meid vermomt zich als een mannelijke krijger om haar vader te redden.', 'Niki Caro', 'aKx1ARwG55zZ0GpRvU2WrGrCG9o.jpg', 'Mulan');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (45, '2020-08-26', 150, 'Met slechts één woord, Tenet, en vechtend voor het voortbestaan van de wereld, onderneemt de Protagonist een missie in een schaduwwereld van internationale spionage.', 'Christopher Nolan', 'k68nPLbIST6NP96JmTxmZijEvCA.jpg', 'Tenet');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (46, '2020-03-06', 102, 'Two elven brothers embark on a quest to bring their father back for one day.', 'Dan Scanlon', 'f4aul3FyD3jv3v4bul1IrkWZvzq.jpg', 'Onward');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (14, '2021-08-06', 132, 'Een groep gevangenen van Task Force X wordt gestuurd op een gevaarlijke missie om de wereld te redden.', 'James Gunn', 'u4GNngraBcCcHVln2Dfq1f1CE59.jpg', 'The Suicide Squad');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (47, '2020-09-25', 130, 'The story of 7 people on trial stemming from various charges surrounding the uprising at the 1968 Democratic National Convention in Chicago, Illinois.', 'Aaron Sorkin', 'ahf5cVdooMAlDRiJOZQNuLqa1Is.jpg', 'The Trial of the Chicago 7');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (48, '2020-01-01', 113, 'An American expat tries to sell off his highly profitable marijuana empire in London, triggering plots, schemes, bribery and blackmail in an attempt to steal his domain out from under him.', 'Guy Ritchie', 'jtrhTYB7xSrJxR1vusu99nvnZ1g.jpg', 'The Gentlemen');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (51, '2020-02-05', 109, 'Na de breuk met de Joker sluit Harley Quinn zich aan bij superhelden Black Canary, Huntress en Renee Montoya om een jong meisje te redden van een misdaadbaas.', 'Cathy Yan', 'h4VB6m0RwcicVEZvzftYZyKXs6K.jpg', 'Birds of Prey');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (62, '2020-07-10', 90, 'Wanneer de zorgeloze Nyles en de terughoudende bruidsmeisje Sarah elkaar ontmoeten op een bruiloft in Palm Springs, wordt alles gecompliceerder als ze vastzitten in een tijdlus.', 'Max Barbakow', 'y55oBgf6bVMI7sFNXwJDrSIxPQt.jpg', 'Palm Springs');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (65, '2020-05-01', 104, 'Verlegen, vlijtige student Ellie wordt ingehuurd door de verlegen maar onhandige jock Paul, die hulp nodig heeft om een populair meisje voor zich te winnen. Maar hun nieuwe en onverwachte vriendschap wordt gecompliceerd als Ellie ontdekt dat ze ook gevoelens heeft voor hetzelfde meisje.', 'Alice Wu', 'wp6OxE4poJ4G7c0U2ZIXasTSMR7.jpg', 'The Half of It');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (67, '2020-12-18', 94, 'De spanningen lopen op wanneer de baanbrekende blueszangeres Ma Rainey en haar band samenkomen in een opnamestudio in Chicago in 1927.', 'George C. Wolfe', 'pvtyxijaBrCSbByXLcUIDDSvc40.jpg', 'Ma Rainey\''s Black Bottom');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (69, '2020-11-11', 116, 'Een dringend telefoontje haalt een Yale-rechtenstudent terug naar zijn ouderlijk huis in Ohio, waar hij terugkijkt op drie generaties familiegeschiedenis en zijn eigen toekomst.', 'Ron Howard', 'zQFjMmE3K9AX5QrBL1SXIxYQ9jz.jpg', 'Hillbilly Elegy');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (70, '2020-12-25', 118, 'Een veteraan uit de Amerikaanse Burgeroorlog stemt ermee in om een meisje, dat jaren geleden door de Kiowa-bevolking is meegenomen, tegen haar wil bij haar tante en oom af te leveren.', 'Paul Greengrass', 'fYQCgVRsQTEfUrP7cW5iAFVYOlh.jpg', 'News of the World');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (71, '2021-10-15', 153, 'Koning Charles VI verklaart dat ridder Jean de Carrouges zijn geschil met zijn schildknaap moet beslechten door hem uit te dagen voor een duel.', 'Ridley Scott', 'zjrJE0fpzPvX8saJXj8VNfcjBoU.jpg', 'The Last Duel');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (72, '2021-02-12', 126, 'Bill O\''Neal infiltreert de Black Panther Party per FBI-agent Mitchell en J. Edgar Hoover. Terwijl de partijvoorzitter Fred Hampton opklimt, ontstaat er een innerlijke strijd in O\''Neal\''s ziel.', 'Shaka King', 'iIgr75GoqFxe1X5Wz9siOODGe9u.jpg', 'Judas and the Black Messiah');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (18, '2021-08-13', 115, 'Een bankbediende ontdekt dat hij eigenlijk een NPC is in een open-wereld videospel, waarna hij besluit zijn eigen verhaal te schrijven.', 'Shawn Levy', 'xmbU4JTUm8rsdtn7Y3Fcm30GpeT.jpg', 'Free Guy');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (15, '2021-12-22', 131, 'In dit prequel-verhaal moeten een groep elite-spionnen vechten om een plan dat miljoenen levens bedreigt te stoppen.', 'Matthew Vaughn', 'nexYoH39YcxmiuhIBdfUwMkMsD4.jpg', 'The King\''s Man');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (17, '2021-11-05', 156, 'Een ras van onsterfelijke wezens moet opstaan om de aarde te beschermen tegen hun oude vijanden.', 'Chloé Zhao', '4wJX8ReBintesY6Mrc0kugIPvNx.jpg', 'Eternals');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (20, '2021-10-15', 153, 'Een vrouw beweert dat ze is verkracht door haar man’s beste vriend, wat leidt tot een duel om de waarheid te achterhalen.', 'Ridley Scott', 'zjrJE0fpzPvX8saJXj8VNfcjBoU.jpg', 'The Last Duel');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (21, '2021-11-19', 144, 'Het inspirerende verhaal van Richard Williams, de vader en coach van de tennissterren Venus en Serena Williams.', 'Reinaldo Marcus Green', 'vjpMd1dsEsVBoUhq6iVHXwwFj9n.jpg', 'King Richard');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (22, '2021-11-24', 158, 'Een Italiaanse mode-imperium wordt verscheurd door verraad, moord en wraakzuchtige intriges.', 'Ridley Scott', 'oJCQjD2byiVF1EG408F9dBn9ndU.jpg', 'House of Gucci');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (23, '2021-11-24', 102, 'Een jong meisje ontdekt dat ze de enige is zonder magische krachten in een familie vol bijzondere gaven.', 'Jared Bush', '4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg', 'Encanto');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (24, '2021-10-22', 108, 'Een groep Amerikaanse journalisten in Frankrijk publiceert een laatste uitgave van hun geliefde tijdschrift.', 'Wes Anderson', '6JXR3KJH5roiBCjWFt09xfgxHZc.jpg', 'The French Dispatch');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (25, '2021-10-29', 117, 'Een jonge vrouw reist mysterieus terug naar het Londen van de jaren \''60, waar ze getuige is van een schokkende moord.', 'Edgar Wright', 'n1ZRmjlk1BJTY7aASqACfPAaLn2.jpg', 'Last Night in Soho');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (27, '2021-07-30', 130, 'Sir Gawain, een neef van koning Arthur, gaat op een epische reis om zichzelf te bewijzen in een wereld van legendarische helden.', 'David Lowery', 'if4hw3Ou5Sav9Em7WWHj66mnywp.jpg', 'The Green Knight');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (29, '2021-08-27', 91, 'Een angstaanjagende legende keert terug om een nieuwe generatie het zwijgen op te leggen in dit ijzingwekkende horrorverhaal.', 'Nia DaCosta', 'qeV15PpR8jFJA9TF9JPXIoqEgp1.jpg', 'Candyman');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (41, '2020-12-23', 118, 'A lone scientist in the Arctic races to contact a crew of astronauts returning home to a mysterious global catastrophe.', 'George Clooney', 'XilJ7FF4U10hiNmWsCmRA6wjJQ.jpg', 'The Midnight Sky');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (49, '2020-06-12', 137, 'Scott is vastgelopen sinds zijn vader, een brandweerman, is overleden. Hij brengt zijn dagen door met blowen en dromen om tatoeëerder te worden, tot gebeurtenissen hem dwingen om met zijn verdriet om te gaan en de eerste stappen vooruit te zetten in het leven.', 'Judd Apatow', 'zQFjMmE3K9AX5QrBL1SXIxYQ9jz.jpg', 'The King of Staten Island');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (50, '2020-07-10', 91, 'Een beginnende kapitein leidt een konvooi van geallieerde schepen met duizenden soldaten over het verraderlijke water van de "Zwarte Put" naar het front van de Tweede Wereldoorlog.', 'Aaron Schneider', 'kjMbDciooTbJPofVXgAoFjfX8Of.jpg', 'Greyhound');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (61, '2020-09-30', 83, 'Met rauwe, eerstehands beelden onderzoekt deze documentaire de verdwijning van Shanann Watts en haar kinderen, en de vreselijke gebeurtenissen die daarop volgden.', 'Jenny Popplewell', 'jjs3hE3mQlVGTX3u5ZH2EJBJpf3.jpg', 'American Murder: The Family Next Door');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (68, '2020-12-11', 132, 'Een groep hilarisch zelfingenomen theatersterren stormt een klein conservatief stadje in Indiana binnen om een middelbare scholier te steunen die haar vriendin mee wil nemen naar het schoolbal.', 'Ryan Murphy', 'i7An8UravfzqaU7SuumaWEVRqVU.jpg', 'The Prom');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (73, '2021-01-15', 112, 'Een archeoloog begint aan de historisch belangrijke opgraving van Sutton Hoo in 1938.', 'Simon Stone', 'dFDNb9Gk1kyLRcconpj7Mc7C7IL.jpg', 'The Dig');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (74, '2019-12-25', 119, 'Twee Britse soldaten krijgen de opdracht om diep in vijandelijk gebied een boodschap over te brengen die 1.600 mannen kan redden van een dodelijke val.', 'Sam Mendes', 'iZf0KyrE25z1sage4SYFLCCrMi9.jpg', '1917');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (75, '2017-11-22', 125, 'In mei 1940 hangt het lot van West-Europa aan een zijden draadje wanneer Winston Churchill moet beslissen of hij met Adolf Hitler gaat onderhandelen of doorvecht, in de wetenschap dat dit het einde van het Britse rijk kan betekenen.', 'Joe Wright', 'xa6G3aKlysQeVg9wOb0dRcIGlWu.jpg', 'Darkest Hour');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (76, '2000-06-28', 165, 'Vredige boer Benjamin Martin wordt gedwongen om het koloniale leger te leiden tijdens de Amerikaanse Revolutie wanneer een sadistische Britse officier zijn zoon vermoordt.', 'Roland Emmerich', 'fWZd815QxUCUcrWQZwUkAp9ljG.jpg', 'The Patriot');
INSERT INTO public.movie (id, release_date, duration, description, director, image_url, title) VALUES (77, '2012-11-09', 150, 'Terwijl de Amerikaanse Burgeroorlog woedt, worstelt president Lincoln met de aanhoudende slachting op het slagveld terwijl hij intern strijdt over de emancipatie van de slaven.', 'Steven Spielberg', '9TaupczRcEkOaYbsiQuLg3kXPLq.jpg', 'Lincoln');

INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (15, 2);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 2);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (8, 2);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 3);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (8, 3);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (15, 3);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (15, 4);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (8, 4);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (7, 4);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (10, 5);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 5);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (8, 5);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (6, 6);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 6);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (7, 6);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 7);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (8, 7);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (15, 7);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 8);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (7, 8);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 9);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (10, 9);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (8, 9);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (15, 10);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 10);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (8, 10);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 11);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (5, 11);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (8, 11);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (10, 12);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (8, 12);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 12);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (8, 13);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 13);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (17, 13);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (8, 14);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (5, 14);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 14);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (8, 15);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (17, 15);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 15);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (5, 16);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (10, 16);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 17);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (8, 17);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (10, 17);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (5, 18);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 18);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (15, 18);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (5, 19);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 19);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (6, 19);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (7, 20);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (4, 21);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (7, 21);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (4, 22);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (6, 22);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (7, 22);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (10, 23);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (9, 23);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (3, 23);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (5, 24);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (7, 24);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (14, 25);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (12, 25);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (17, 25);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (10, 27);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (7, 27);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (8, 27);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (17, 28);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (12, 28);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (12, 29);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (17, 29);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (12, 30);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (17, 30);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (12, 31);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (17, 31);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (12, 32);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (14, 32);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (17, 32);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (17, 33);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 33);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (9, 34);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (3, 34);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (10, 34);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (10, 35);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 35);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (8, 36);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 36);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (10, 37);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (8, 37);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 37);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (15, 38);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 38);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (8, 38);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (8, 39);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (10, 39);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 40);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (8, 40);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (15, 40);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (15, 41);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (7, 41);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (17, 41);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (9, 42);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (3, 42);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (13, 42);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (10, 43);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 43);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (8, 43);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (10, 44);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (7, 44);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 44);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (15, 45);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 45);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (17, 45);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (3, 46);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (5, 46);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (8, 46);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (7, 47);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 48);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (6, 48);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (5, 48);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (7, 49);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (5, 49);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (18, 50);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 50);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (7, 50);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (5, 51);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (6, 51);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 51);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (6, 61);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (20, 61);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (5, 62);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (5, 65);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (7, 67);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (13, 67);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (5, 68);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (13, 68);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (7, 69);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (19, 70);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (7, 70);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 71);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (7, 71);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (7, 72);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (6, 72);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (7, 73);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (18, 74);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (7, 74);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (7, 75);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (18, 75);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (18, 76);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (2, 76);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (7, 76);
INSERT INTO public.movie_genres (genre_id, movie_id) VALUES (7, 77);

INSERT INTO public.users (username, address, apikey, email, enabled, password, profile_url) VALUES ('user', NULL, 'YEkL4NEWt6IpQOrA630x', 'user@user.nl', true, '$2a$10$LjhJTVjGm9vbw43c3I6bC.MpQbsUpOqpRDCDwBCMzkH6T/tf3RSBO', 'empty');
INSERT INTO public.users (username, address, apikey, email, enabled, password, profile_url) VALUES ('root', NULL, 'J7B1Gj4fmJKH4GEAXZCs', 'root@root.nl', true, '$2a$10$aJPprhPLDaU4s8wEgg6i8.wtQpg1AUwwZRfk3CwlezsYrCXXFWYJC', 'empty');














